export default {
  color: {
    main: '#D9463E',
    background: '#FFFFFF',
    text: '#adacac',
  },
  images: {
    apple: require('../assets/images/logo_apple.jpg'),
    left: require('../assets/images/ic_left.png'),
    facebook: require('../assets/images/logo_facebook.png'),
    lamborghini: require('../assets/images/logo_lamborghini.png'),
    zalo: require('../assets/images/logo_zalo.png'),
    img595097: require('../assets/images/img_595097.jpg'),
    mercedes: require('../assets/images/img_mercedes.jpg'),
    bmw: require('../assets/images/img_bmw.png'),
    score: require('../assets/images/score.png'),
    assists: require('../assets/images/98611.png'),
    yellowcard: require('../assets/images/yellowcard.png'),
    redcard: require('../assets/images/redcard.png'),
  },
  fonts: {
    notoSansJPBold: 'NotoSansJP-Bold',
  },
  screenName: {
    Home: 'HomeScreen',
    Login: 'LoginScreen',
    Detail: 'DetailScreen',
    Users: 'UsersScreen',
    UserDetail: 'UserDetailScreen',
    Match: 'MatchScreen',
    Charts: 'ChartsScreen',
    Statistics: 'StatisticsScreen',
    Players: 'PlayersScreen',
    Teams: 'ListPlayer',
    DetailPlayer: 'DetailPlayer',
    ProfilePlayer: 'ProfilePlayer',
    FixtureDetails: 'FixtureDetailsScreen',
    RootTabNavigator: 'RootTabNavigator',
    Search: 'SearchScreen',
    MathTeam: 'MathTeamScreen',
  },
};
